#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
import sys
import time
import traceback
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from worker_common import build_file_logger, load_json, normalize_whitespace, slugify, write_json
from cuda_devices import default_torch_device, format_cuda_devices, first_configured_cuda_devices

from review.persona import DEFAULT_PERSONA_SUBJECT, select_random_persona


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run one author_background reviewer worker.")
    parser.add_argument("--input-file", required=True, help="JSON payload for one reviewer worker.")
    parser.add_argument("--work-dir", required=True, help="Directory for artifacts and result.json.")
    parser.add_argument("--cuda-visible-devices", default=None, help="Optional CUDA_VISIBLE_DEVICES override.")
    parser.add_argument("--smoke", action="store_true", help="Write stub artifacts without running the real flow.")
    return parser


def run_smoke(payload: dict[str, Any], work_dir: Path) -> dict[str, Any]:
    author_name = normalize_whitespace(payload.get("author_name")) or normalize_whitespace(payload.get("author_id"))
    persona_subject = normalize_whitespace(payload.get("persona_subject")) or DEFAULT_PERSONA_SUBJECT
    persona = select_random_persona(subject=persona_subject)
    profile_dir = work_dir / f"merged_{slugify(author_name)}"
    profile_dir.mkdir(parents=True, exist_ok=True)
    summary_path = profile_dir / "author_summary.json"
    write_json(
        summary_path,
        {
            "author_name": author_name,
            "author_id": normalize_whitespace(payload.get("author_id")),
            "summary": [
                "Smoke reviewer background generated by reviewer_background_worker.",
                f"Idea anchor: {normalize_whitespace(payload.get('idea_text'))[:200]}",
            ],
            "persona": persona,
            "source": "smoke",
        },
    )
    return {
        "status": "ok",
        "mode": "smoke",
        "author_name": author_name,
        "author_id": normalize_whitespace(payload.get("author_id")),
        "persona_subject": persona_subject,
        "summary_path": str(summary_path),
        "work_dir": str(work_dir),
    }


def run_real(payload: dict[str, Any], work_dir: Path, cuda_visible_devices: str | None) -> dict[str, Any]:
    from review.author_background import AuthorBackgroundConfig, run_author_background

    author_name = normalize_whitespace(payload.get("author_name"))
    author_id = normalize_whitespace(payload.get("author_id"))
    search_method = normalize_whitespace(payload.get("search_method")) or ("id" if author_id else "name")
    target_author = author_id if search_method == "id" and author_id else (author_name or author_id)
    if not target_author:
        raise ValueError("Worker payload must contain author_name or author_id")

    if cuda_visible_devices:
        os.environ["CUDA_VISIBLE_DEVICES"] = cuda_visible_devices
    configured_devices = first_configured_cuda_devices()
    device = normalize_whitespace(payload.get("device")) or default_torch_device()

    config = AuthorBackgroundConfig(
        target_author=target_author,
        target_idea=normalize_whitespace(payload.get("idea_text")),
        output_root=work_dir,
        search_method=search_method,
        env_path=Path(payload["env_path"]).expanduser().resolve() if payload.get("env_path") else None,
        llm_api_key=payload.get("llm_api_key"),
        device=device,
        persona_subject=normalize_whitespace(payload.get("persona_subject")) or DEFAULT_PERSONA_SUBJECT,
        persona_prompts_path=(
            Path(payload["persona_prompts_path"]).expanduser().resolve()
            if payload.get("persona_prompts_path")
            else None
        ),
    )
    result = run_author_background(config)

    return {
        "status": result["status"],
        "mode": "real",
        "author_name": author_name,
        "author_id": author_id,
        "summary_path": result["summary_path"],
        "relevant_papers_path": result["relevant_papers_path"],
        "target_folder": result["target_folder"],
        "persona_subject": result.get("persona_subject"),
        "persona_prompts_path": result.get("persona_prompts_path"),
        "work_dir": str(work_dir),
        "device": device,
        "cuda_devices": format_cuda_devices(configured_devices),
    }


def main() -> int:
    args = build_parser().parse_args()
    started_at = time.perf_counter()
    input_path = Path(args.input_file).resolve()
    work_dir = Path(args.work_dir).resolve()
    work_dir.mkdir(parents=True, exist_ok=True)
    logger = build_file_logger(work_dir / "worker.log", Path(__file__).name)
    payload = load_json(input_path)
    logger.info(
        "Worker started mode=%s input_file=%s work_dir=%s cuda_visible_devices=%s",
        "smoke" if args.smoke else "real",
        input_path,
        work_dir,
        args.cuda_visible_devices or os.environ.get("CUDA_VISIBLE_DEVICES", ""),
    )

    result_path = work_dir / "result.json"
    try:
        if args.smoke:
            result = run_smoke(payload, work_dir)
        else:
            result = run_real(payload, work_dir, args.cuda_visible_devices)
        result["elapsed_ms"] = round((time.perf_counter() - started_at) * 1000, 1)
        write_json(result_path, result)
        logger.info(
            "Worker finished status=%s elapsed_ms=%s result_path=%s",
            result.get("status"),
            result.get("elapsed_ms"),
            result_path,
        )
        return 0
    except Exception as exc:
        error_payload = {
            "status": "error",
            "mode": "smoke" if args.smoke else "real",
            "error_type": exc.__class__.__name__,
            "error": str(exc),
            "traceback": traceback.format_exc(),
            "elapsed_ms": round((time.perf_counter() - started_at) * 1000, 1),
        }
        write_json(result_path, error_payload)
        logger.exception("Worker failed error=%s", exc)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
